### ISSUE TITLE
Research CSS Improvements

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#1081]
### Description / User story

We have a few CSS improvements already planned in the backlog (see https://github.com/deven-org/boiler/milestone/21), but we should take some time first to decide, which of these are really important right now, after the implementation of #740 , to make sure the new theming approach works, won't break and can be easily used.

Timebox: 1 Iteration

### Requirements / Prerequisites

- none

### Acceptance Criteria

- [x] We did research about CSS improvements
- [x] The outcome has been documented
- [x] A decision has been made which improvements we should focus on and implement in the next iterations
- [x] Follow-Up tasks have been prepared

### Additional information

- ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faselbaum** [comment]
# ⚠️ WIP

# Areas of Research and Findings
At the time of writing i have researched the following areas for potential CSS improvements.

## Use a CSS-IN-JS Library
To improve the developer experience and minimise bugs it's worth investigating some of the bigger css-in-js libraries as they often come with extra tooling for css validation, editor syntax highlighting and editor autocompletion.

I took a peek at the following libraries:
- [linaria](https://linaria.dev/) - 9.3k ⭐ on GitHub
- [vanilla-extract](https://vanilla-extract.style/) - 11.2k ⭐ on GitHub
- [emotion](https://emotion.sh/) - 17.2k ⭐ on GitHub

### Linaria
On first glance linaria seemed to be a good fit as we are currently dealing with mostly "static" styles in our css codebase and linaria advertises itself as a static style extraction tool.

On further investigation it turned out that linaria is incompatible with semi dynamic template expressions as currently employed through our `TokenIterator` concept. The linaria webpack plugin will throw an error when trying to call a function inside a css template literal which completely negates the usefulness of combining javascript and css.

### vanilla-extract
I only did a high-level investigation by looking at the docs. It has a few promising features but also a few shortcomings.

**Pros**
- Extracts static styles. Good fit for our current `classMap` approach.
- Doesn't require an extra formatter or linter since it's using an object style API instead of tagged template literals. That means it integrates well with TypeScript, Prettier and ESLint.

**Cons**
- Requires extra build tooling configuration (e.g. webpack plugin) to extract and inject styles.
- We'd have to re-write our entire css to use style objects.
