### ISSUE TITLE
Input Field Number - native stepper is shown next to custom stepper in firefox

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/boiler#1117]
### What is affected?

Component

### Description

When I open the Input Field Number component in Storybook on Firefox, I expect to see the same stepper as in other browsers, instead I see an additional native stepper next to the custom one.

### Steps to reproduce

1. Open Input Field Number component in Storybook on Firefox (open https://b01ler.onrender.com/?path=/story/components-input-field-number--input-field-number on Firefox)
2. See 2 steppers

### Affected version(s)

current develop version

### Operating system / Browser / Environment

macOS: 14.4.1 (23E224), Browser: Firefox 125.0.3 (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bar-tay** [comment]
@thrbnhrtmnn In my current browser version (130.0 64-bit), the issue was no longer present. Nevertheless, I've added something to ensure it doesn't appear in the older version either. Unfortunately, I can't test this because I can't access to the older Firefox version.
We can see if it works after the merge.
